name: 'include what you use Github action'
author: 'Emil Gedda'
branding:
  icon: 'align-left'
  color: 'blue'
description: 'Run include what you use on your code'
inputs:
  compilation-database-path:
    description: 'Relative path to directory containing the compilation database'
    required: false
    default: '.'
  output-format:
    description: 'Output format of the include suggestions (clang|iwyu)'
    required: false
    default: 'iwyu'
  no-error:
    description: 'The action succeeds regardless if there are include suggestions or not'
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'docker://gedda/include-what-you-use-action:1.0'
  args:
    - ${{ inputs.compilation-database-path }}
    - ${{ inputs.output-format }}
    - ${{ inputs.no-error }}
